-- Add macro goal columns to profiles table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS protein_goal INTEGER NOT NULL DEFAULT 150,
ADD COLUMN IF NOT EXISTS carbs_goal INTEGER NOT NULL DEFAULT 250,
ADD COLUMN IF NOT EXISTS fats_goal INTEGER NOT NULL DEFAULT 65;